{"created": 1720632504.2767012, "duration": 19.669450283050537, "exitcode": 0, "root": "C:\\Users\\Administrator\\Automation\\Tests", "environment": {}, "summary": {"passed": 1, "total": 1, "collected": 1}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": "test_AddMoney.py", "type": "Module"}]}, {"nodeid": "test_AddMoney.py", "outcome": "passed", "result": [{"nodeid": "test_AddMoney.py::test_add_money", "type": "Coroutine", "lineno": 7}]}], "tests": [{"nodeid": "test_AddMoney.py::test_add_money", "lineno": 7, "outcome": "passed", "keywords": ["test_add_money", "qa", "asyncio", "regression", "pytestmark", "test_AddMoney.py", "__init__.py", "Tests"], "setup": {"duration": 0.004317400045692921, "outcome": "passed"}, "call": {"duration": 19.618010099977255, "outcome": "passed", "stdout": "<Page url='https://demo2.okoora.com/login'>\nhttps://okoora-demo-api2023.azurewebsites.net/api/Authentication/RefreshToken?refreshToken=undefined 400 {\n  \"apiErrorCode\": 1500,\n  \"apiErrorMessage\": [\n    \"The value 'undefined' is not valid.\"\n  ]\n}\nWaiting for response...\nResponse received.\nWaiting for response...\nResponse received.\nhttps://okoora-demo-api2023.azurewebsites.net/api/Balances/DepositRegular?Currency=ILS&Amount=10,000&OkooraBankId=2&BeneficiaryId=3c3549d3-8a31-4ce4-ac3a-047cd37849b2&TransferType=3&TransferAt= 201 \"fa6f5963-ee54-4bb9-ada8-7fe7a4385bbd\"\n", "log": [{"name": "asyncio", "msg": "Exception in callback AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe... 1 (char 0)')>) at C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pyee\\asyncio.py:69\nhandle: <Handle AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe... 1 (char 0)')>) at C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pyee\\asyncio.py:69>", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\base_events.py", "filename": "base_events.py", "module": "base_events", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pyee\\asyncio.py\", line 77, in callback\n    self.emit(\"error\", exc)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pyee\\base.py\", line 211, in emit\n    self._emit_handle_potential_error(event, args[0] if args else None)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pyee\\base.py\", line 169, in _emit_handle_potential_error\n    raise error\n  File \"C:\\Users\\Administrator\\Automation\\Tests\\test_AddMoney.py\", line 34, in on_response\n    result = await response.json()\n             ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\playwright\\async_api\\_generated.py\", line 636, in json\n    return mapping.from_maybe_impl(await self._impl_obj.json())\n                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\playwright\\_impl\\_network.py\", line 590, in json\n    return json.loads(await self.text())\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\json\\__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\json\\decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\json\\decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)", "stack_info": null, "lineno": 1757, "funcName": "default_exception_handler", "created": 1720632491.1281996, "msecs": 128.0, "relativeCreated": 7643.787145614624, "thread": 2592, "threadName": "MainThread", "processName": "MainProcess", "process": 10564}, {"name": "asyncio", "msg": "Exception in callback AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe... 1 (char 0)')>) at C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pyee\\asyncio.py:69\nhandle: <Handle AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe... 1 (char 0)')>) at C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pyee\\asyncio.py:69>", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\base_events.py", "filename": "base_events.py", "module": "base_events", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pyee\\asyncio.py\", line 77, in callback\n    self.emit(\"error\", exc)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pyee\\base.py\", line 211, in emit\n    self._emit_handle_potential_error(event, args[0] if args else None)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pyee\\base.py\", line 169, in _emit_handle_potential_error\n    raise error\n  File \"C:\\Users\\Administrator\\Automation\\Tests\\test_AddMoney.py\", line 34, in on_response\n    result = await response.json()\n             ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\playwright\\async_api\\_generated.py\", line 636, in json\n    return mapping.from_maybe_impl(await self._impl_obj.json())\n                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\playwright\\_impl\\_network.py\", line 590, in json\n    return json.loads(await self.text())\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\json\\__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\json\\decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\json\\decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)", "stack_info": null, "lineno": 1757, "funcName": "default_exception_handler", "created": 1720632491.1301913, "msecs": 130.0, "relativeCreated": 7645.7788944244385, "thread": 2592, "threadName": "MainThread", "processName": "MainProcess", "process": 10564}]}, "teardown": {"duration": 0.001264600083231926, "outcome": "passed"}}], "warnings": [{"message": "There is no current event loop", "category": "DeprecationWarning", "when": "runtest", "filename": "C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pytest_asyncio\\plugin.py", "lineno": 894}, {"message": "There is no current event loop", "category": "DeprecationWarning", "when": "runtest", "filename": "C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pytest_asyncio\\plugin.py", "lineno": 676}]}